version: '3.9'

services:
  php:
    image: php_for_bulletin_board
    working_dir: /home/app
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    tty: true
    stdin_open: true
    stop_signal: SIGKILL
    restart: unless-stopped
    environment:
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_NAME: 'attendance_manager'
      DB_USER: 'nagi'
      DB_PASS: 'password79'
    ports:
      - ${PORT:-7070}:80
    volumes:
      - .:/home/app

  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password79
      MYSQL_DATABASE: attendance_manager
      MYSQL_USER: nagi
      MYSQL_PASSWORD: password79
    ports:
      - 3306
    volumes:
      - db-data:/var/lib/mysql

  myadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: nagi
      PMA_PASSWORD: password79
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${DB_ADMIN_PORT:-7071}:80

volumes:
  db-data: